version: '2'

services:
  web:
    build: ./
    container_name: dir_container
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    container_name: dir_nginx_container
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
